# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0010_auto_20161120_0802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set([('user', 'category')]),
        ),
    ]
