# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans', '0011_auto_20161205_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
