# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans', '0013_categoryrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Figure, please use the format: <em>dd.cc</em>', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Vendor name'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryrule',
            unique_together=set([('category', 'keyword')]),
        ),
    ]
