# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beans', '0015_auto_20170114_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category name'),
        ),
    ]
