# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0017_category_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'user')]),
        ),
    ]
