# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beans', '0018_auto_20170116_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categoryrule',
            unique_together=set([('category', 'keyword', 'user')]),
        ),
    ]
